### ISSUE TITLE
Probleme dans le LoginController

### ISSUE THREAD

**Issue by giovanne3u** [Kebatoufragile/Videodorant#11]
Grosse erreur quand on se trompe d'adresse email, à fixer au plus vite !!!!

**Comment by giovanne3u** [comment]
Pareil quand on se trompe dans le mdp

**Comment by giovanne3u** [comment]
@Kixot tu pourras jeter un œil dessus ? Je comprends pas vraiment pourquoi la méthode authenticate de Sentinel me renvoie une erreur comme ça. Apparemment c'est un problème d'insertion dans la table throttle.

**Comment by Kixot** [comment]
Ah oui je l'avais eue hier je regarderai en anglais

**Comment by Kixot** [comment]
```
            $credentials = [
                'email' => filter_var($_POST['email'], FILTER_SANITIZE_EMAIL),
                'password' => filter_var($_POST['password'], FILTER_SANITIZE_STRING)
            ];
```
Les filtres sont pas mis entre parenthèses donc ça envoie un id 0 par défaut à la bdd

**Comment by Kixot** [comment]
[FIXED]

La clé user_id dans la table throttle ne pouvait pas être nulle, sauf que quand quelqu'un essaye de se connecter et échoue, l'ID doit être nulle du coup mysql mettait 0 à la place donc on avait une erreur de clé dupliquée (parce que l'action se fait 2 fois avec les méthodes authenticate et login)

**Comment by giovanne3u** [comment]
Ok lourd
