### ISSUE TITLE
[BUG] Stream

### ISSUE THREAD

**Issue by giovanne3u** [Kebatoufragile/Videodorant#24]
Le script PHP attend la fin de l'éxécution de la commande (StreamController.php:l87), il faudrait que le script continue en lancant la commande en arrière plan

**Comment by giovanne3u** [comment]
Plus vraiment le même problème, la commande ne se lance plus. @Kixot regarde un coup peut-être que tu trouveras quelque chose

**Comment by Kixot** [comment]
Oui j'arrive Arsène
